import type { Metadata } from "next";
import { LegalPageShell } from "@/components/legal-page-shell";

export const metadata: Metadata = {
  title: "Terms of Service — SyncPilot",
  description:
    "Terms and conditions for using SyncPilot's Gmail-to-Signal AI summarization service.",
};

const LAST_UPDATED = "June 9, 2026";

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" lastUpdated={LAST_UPDATED}>
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use
        of SyncPilot AI (&quot;SyncPilot,&quot; &quot;we,&quot; &quot;us,&quot;
        or &quot;our&quot;), an AI agent that connects Gmail and Signal to
        deliver inbox summaries. By creating an account or using SyncPilot, you
        agree to these Terms.
      </p>

      <section>
        <h2>1. Description of Service</h2>
        <p>SyncPilot provides:</p>
        <ul>
          <li>Read-only Gmail integration via Composio (Google OAuth)</li>
          <li>AI-generated summaries of new email messages using Groq</li>
          <li>Delivery of summaries to a Signal number you configure</li>
          <li>A dashboard to manage integrations and view run history</li>
          <li>
            An optional Agent Console for on-demand AI-assisted workflows using
            content you provide
          </li>
        </ul>
        <p>
          The service runs on a scheduled basis (typically every 5–15 minutes)
          when configured with an external cron trigger.
        </p>
      </section>

      <section>
        <h2>2. Eligibility</h2>
        <p>
          You must be at least 13 years old and able to form a binding contract
          to use SyncPilot. You are responsible for ensuring your use complies
          with applicable laws, including those governing email access and
          messaging in your jurisdiction.
        </p>
      </section>

      <section>
        <h2>3. Account Registration</h2>
        <p>
          You sign in with Google. You are responsible for maintaining the
          security of your account credentials and for all activity under your
          account. Notify us promptly if you suspect unauthorized access.
        </p>
      </section>

      <section>
        <h2>4. Third-Party Integrations</h2>
        <p>
          SyncPilot requires connections to third-party services. By connecting
          an integration, you authorize SyncPilot to access and process data as
          described in our{" "}
          <a href="/privacy" className="text-[#A089E6] underline-offset-2 hover:underline">
            Privacy Policy
          </a>
          :
        </p>
        <ul>
          <li>
            <strong>Gmail (via Composio):</strong> You grant read-only access to
            fetch new messages. The connection and its Google OAuth tokens are
            brokered and managed by Composio. You may revoke access at any time
            through Settings or your Google Account permissions.
          </li>
          <li>
            <strong>Composio:</strong> Manages the Gmail connection and the
            Google OAuth tokens used to fetch your messages on your behalf.
          </li>
          <li>
            <strong>Signal:</strong> You link a device by scanning a QR code and
            provide sender and recipient phone numbers. You are responsible for
            ensuring you have permission to send messages to the configured
            recipient.
          </li>
          <li>
            <strong>Groq:</strong> Email content and agent prompts are sent to
            Groq for AI processing.
          </li>
        </ul>
        <p>
          We are not responsible for outages, policy changes, or actions taken by
          third-party providers.
        </p>
      </section>

      <section>
        <h2>5. AI-Generated Content</h2>
        <p>
          Summaries and agent responses are generated by artificial intelligence
          and may be incomplete, inaccurate, or misleading. SyncPilot does not
          guarantee the correctness of AI output. You should review important
          information in your original emails and not rely solely on AI summaries
          for critical decisions.
        </p>
      </section>

      <section>
        <h2>6. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use SyncPilot to access email accounts you do not own or lack permission to access</li>
          <li>Send spam, harassing, or unlawful content through Signal delivery</li>
          <li>Attempt to bypass security measures or abuse API endpoints</li>
          <li>Reverse engineer, scrape, or overload the service</li>
          <li>Use the service in violation of Google, Composio, Signal, Groq, or applicable law</li>
        </ul>
        <p>
          We may suspend or terminate access if we reasonably believe you have
          violated these Terms.
        </p>
      </section>

      <section>
        <h2>7. Intellectual Property</h2>
        <p>
          SyncPilot, its branding, and original software are owned by SyncPilot
          AI and its contributors. The project is released under the MIT
          License. These Terms do not grant you ownership of our trademarks,
          logos, or proprietary service components beyond what the open-source
          license permits.
        </p>
      </section>

      <section>
        <h2>8. Service Availability</h2>
        <p>
          SyncPilot is provided on an &quot;as available&quot; basis. We do not
          guarantee uninterrupted access. Maintenance, third-party outages,
          rate limits, or configuration issues may affect delivery of summaries.
        </p>
      </section>

      <section>
        <h2>9. Disclaimer of Warranties</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, SYNCPILOT IS PROVIDED &quot;AS
          IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND,
          WHETHER EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
          NON-INFRINGEMENT.
        </p>
      </section>

      <section>
        <h2>10. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, SYNCPILOT AI AND ITS
          OPERATORS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
          CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, PROFITS, OR
          GOODWILL, ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY
          FOR ANY CLAIM RELATED TO THE SERVICE IS LIMITED TO THE GREATER OF
          (A) THE AMOUNT YOU PAID US IN THE TWELVE MONTHS BEFORE THE CLAIM, OR
          (B) USD $100.
        </p>
        <p>
          Some jurisdictions do not allow certain limitations, so some of the
          above may not apply to you.
        </p>
      </section>

      <section>
        <h2>11. Termination</h2>
        <p>
          You may stop using SyncPilot at any time by disconnecting integrations
          and discontinuing use. We may suspend or terminate your access for
          violations of these Terms, security risks, or operational reasons.
          Sections that by their nature should survive termination (including
          disclaimers and limitations of liability) will continue to apply.
        </p>
      </section>

      <section>
        <h2>12. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. The &quot;Last
          updated&quot; date at the top reflects the current version. Material
          changes will be posted on this page. Continued use after changes
          constitutes acceptance of the revised Terms.
        </p>
      </section>

      <section>
        <h2>13. Governing Law</h2>
        <p>
          These Terms are governed by applicable law in the jurisdiction where
          SyncPilot is operated, without regard to conflict-of-law principles.
          Disputes will be resolved in the courts of that jurisdiction, unless
          otherwise required by mandatory local law.
        </p>
      </section>

      <section>
        <h2>14. Contact</h2>
        <p>
          Questions about these Terms can be submitted through the{" "}
          <a
            href="https://github.com/prawesh-12/sync-pilot/issues"
            className="text-[#A089E6] underline-offset-2 hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            SyncPilot GitHub repository
          </a>
          .
        </p>
      </section>
    </LegalPageShell>
  );
}
